services:
  - type: web
    name: auction-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn auction_bot.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "auction-bot.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: auction-bot-db
          property: connectionString

databases:
  - name: auction-bot-db
    plan: free

